use_frameworks!

platform :ios, '8.0'

target 'YJShowView_Example' do
  pod 'YJShowView', :path => '../'

  target 'YJShowView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
